// Auto-generated file - DO NOT EDIT MANUALLY
// This file is generated by scripts/generate-tool-imports.js
// It ensures all tool module augmentations are loaded for TypeScript autocomplete

import '@tools/hello-world';
import '@tools/ocr';
import '@tools/screenshot';

// This export is required to make this a module
export {};
